# Generated by Django 5.0.1 on 2025-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.IntegerField(blank=True, null=True)),
                ('clase_de_aviso', models.CharField(blank=True, max_length=10, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('ubicacion_tecnica', models.CharField(blank=True, max_length=100, null=True)),
                ('denominacion_de_objeto_tecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('pto_tbjo_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_deseado', models.DateField(blank=True, null=True)),
                ('fin_deseado', models.DateField(blank=True, null=True)),
                ('sociedad', models.CharField(blank=True, max_length=10, null=True)),
                ('status_de_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_1', models.IntegerField(blank=True, null=True)),
                ('clase_de_orden', models.CharField(blank=True, max_length=10, null=True)),
                ('revision', models.CharField(blank=True, max_length=10, null=True)),
                ('ubicacion_tecnica_1', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_breve', models.CharField(blank=True, max_length=100, null=True)),
                ('pto_tbjo_responsable_1', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_de_inicio_extrema', models.DateField(blank=True, null=True)),
                ('fecha_fin_extrema', models.DateField(blank=True, null=True)),
                ('tota_general_plan', models.FloatField(blank=True, null=True)),
                ('total_general_real', models.FloatField(blank=True, null=True)),
                ('indicador_ABC', models.CharField(blank=True, max_length=10, null=True)),
                ('status_del_sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('sociedad_CO', models.CharField(blank=True, max_length=10, null=True)),
                ('planes_trab', models.CharField(blank=True, max_length=10, null=True)),
                ('clase_consignacion', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('ub_tecnica_busqueda', models.CharField(blank=True, max_length=100, null=True)),
                ('denominacion_de_la_revision', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inic_revision', models.DateField(blank=True, null=True)),
                ('hora_inic_revision', models.FloatField(blank=True, null=True)),
                ('fecha_fin_revision', models.DateField(blank=True, null=True)),
                ('hora_fin_revision', models.FloatField(blank=True, null=True)),
                ('desc_jefe_trab', models.CharField(blank=True, max_length=100, null=True)),
                ('st', models.CharField(blank=True, max_length=10, null=True)),
                ('instalacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
