# Generated by Django 5.0.1 on 2026-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrossap',
            name='aviso_criticidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='campo_clasificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='creador_por',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='criticidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='deno_punto_medida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='denominacion_de_objeto_tecnico_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='denominacion_de_objeto_tecnico_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='documento_medicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='equipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='equipo_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='fecha_criticidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='fin_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='hora_medicion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='indicador_abc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='inicio_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='punto_medida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='tipo_objeto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='ubicacion_tecnica_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrossap',
            name='ubicacion_tecnica_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
