from django.db import models

class RegistrosSAP(models.Model):
    # nombre = models.CharField(max_length=100)
    # fecha_registro = models.DateField()
    # puntaje = models.IntegerField()
    aviso = models.IntegerField(null=True, blank=True)
    clase_de_aviso = models.CharField(max_length=10,null=True, blank=True)
    orden = models.IntegerField(null=True, blank=True)
    ubicacion_tecnica = models.CharField(max_length=100,null=True, blank=True)
    denominacion_de_objeto_tecnico = models.CharField(max_length=100,null=True, blank=True)
    descripcion = models.CharField(max_length=100,null=True, blank=True)
    pto_tbjo_responsable = models.CharField(max_length=20,null=True, blank=True)
    inicio_deseado = models.DateField(null=True, blank=True)
    fin_deseado = models.DateField(null=True, blank=True)
    sociedad = models.CharField(max_length=10,null=True, blank=True)
    status_de_usuario = models.CharField(max_length=100,null=True, blank=True)
    orden_1 = models.IntegerField(null=True, blank=True)
    clase_de_orden = models.CharField(max_length=10,null=True, blank=True)
    revision = models.CharField(max_length=10,null=True, blank=True)
    ubicacion_tecnica_1 = models.CharField(max_length=100,null=True, blank=True)
    texto_breve = models.CharField(max_length=100,null=True, blank=True)
    pto_tbjo_responsable_1 = models.CharField(max_length=20,null=True, blank=True)
    fecha_de_inicio_extrema = models.DateField(null=True, blank=True)
    fecha_fin_extrema = models.DateField(null=True, blank=True)
    tota_general_plan = models.FloatField(null=True, blank=True)
    total_general_real = models.FloatField(null=True, blank=True)
    indicador_ABC = models.CharField(max_length=10,null=True, blank=True)
    status_del_sistema = models.CharField(max_length=100,null=True, blank=True)
    sociedad_CO = models.CharField(max_length=10,null=True, blank=True)
    planes_trab = models.CharField(max_length=10,null=True, blank=True)
    clase_consignacion = models.CharField(max_length=10,null=True, blank=True)
    estado = models.IntegerField(null=True, blank=True)
    ub_tecnica_busqueda = models.CharField(max_length=100,null=True, blank=True)
    denominacion_de_la_revision = models.CharField(max_length=100,null=True, blank=True)
    fecha_inic_revision = models.DateField(null=True, blank=True)
    hora_inic_revision = models.FloatField(null=True, blank=True)
    fecha_fin_revision = models.DateField(null=True, blank=True)
    hora_fin_revision = models.FloatField(null=True, blank=True)
    desc_jefe_trab = models.CharField(max_length=100,null=True, blank=True)
    st = models.CharField(max_length=10,null=True, blank=True)
    instalacion = models.CharField(max_length=10,null=True, blank=True)

    def __str__(self):
        return f"{self.aviso} ({self.st})"
